In [ ]:
# This is an example snippet!
# To create your own, add a new snippet block to the
# snippets.json file in your jupyter nbextensions directory:
# /nbextensions/snippets/snippets.json
import this

In [1]:
import numpy as np

# Eigenvalues
M = np.array([[1, 0, 0],
              [0, 2, 0],
              [0, 0, 3]])
vals, vecs = np.linalg.eig(M)
vals

array([1., 2., 3.])

In [2]:
# Eigenvectors - Note, the eigenvectors are the columns of the output.
M = np.array([[1, 0, 0],
              [0, 2, 0],
              [0, 0, 3]])
vals, vecs = np.linalg.eig(M)
vecs 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
M = np.array([[0, 1, 0,0],
              [1, 0, 0,0],
              [0, 0, 0,1],
              [0,0,1,0]])
vals, vecs = np.linalg.eig(M)
vals

array([ 1., -1.,  1., -1.])

In [5]:
M = np.array([[0, 1, 0,0],
              [1, 0, 0,0],
              [0, 0, 0,1],
              [0,0,1,0]])
vals, vecs = np.linalg.eig(M)
vecs

array([[ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.70710678,  0.70710678]])

In [10]:
M = np.array([[1.5,-1],[-0.5,0.5]])
vals, vecs = np.linalg.eig(M)
vecs

array([[ 0.9390708 ,  0.59069049],
       [-0.34372377,  0.80689822]])

In [14]:
M = np.array([[1.5,-1],
              [-0.5,0.5]])
vals, vecs = np.linalg.eig(M)
vals

array([1.8660254, 0.1339746])

In [ ]:
x = input("enter.")